---
version: 2.1

commands:
  run_with_languages:
    description: "Run the given command in an environment that includes relevant langauges in the PATH"
    parameters:
      command:
        type: string
        description: "What command to execute"
      label:
        type: string
        description: "What to label the run"
        default: <<parameters.command>>
    steps:
      - run:
          name: <<parameters.label>>
          command: |
            export PATH="${HOME}/.pyenv/bin:${PATH}"
            export PATH="${HOME}/.rbenv/bin:${HOME}/.rbenv/shims:${PATH}"
            export PATH="${HOME}/project/node_modules/.bin:${PATH}"
            eval "$(pyenv init --path)"
            eval "$(pyenv virtualenv-init -)"
            eval "$(rbenv init -)"
            # keep this in a single place for both main and child builds for cachability
            export BUNDLE_PATH="$(pwd)/vendor/bundle"

            <<parameters.command>>
          environment:
            # https://app.circleci.com/pipelines/github/apiology/cookiecutter-pypackage/4/workflows/29074dc8-944c-4600-8aaa-5116575fed90/jobs/4
            "LC_ALL": "C.UTF-8"
            "LANG": "C.UTF-8"
          no_output_timeout: "20m"
  set_up_environment:
    description: "Install source environment"
    steps:
      - checkout
      - restore_cache:
          key: gems-v2-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          key: wheels-v1-3.12.1-{{ checksum "requirements_dev.txt" }}
      - run:
          name: Initialize packages
          command: |
            export BUNDLE_PATH=vendor/bundle
            './fix.sh'
      - run:
          name: Verify Gemfile.lock
          command: |
            if ! git diff --exit-code Gemfile.lock
            then
              >&2 echo "Please resolve changes to Gemfile.lock after bundle install to avoid caching difficulties"
              exit 1
            fi
      - save_cache:
          key: gems-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - "vendor/bundle"
      - save_cache:
          key: wheels-v1-3.12.1-{{ checksum "requirements_dev.txt" }}
          paths:
            - "/home/circleci/.cache/pip/wheels"
            - "/home/circleci/.pyenv/versions/3.12.1/envs/cookiecutter-ruby-3.12.1"
            - "/home/circleci/.pyenv/versions/cookiecutter-ruby-3.12.1"
      - run:
          name: Download new circleci tool
          command: |
            curl -fLSs \
            https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | sudo bash
  overcommit:
    description: "Run overcommit"
    steps:
      - set_up_environment
      - run_with_languages:
          label: Run overcommit
          command: |
            # Coax overcommit into working
            git config --global user.email "test@test.test"
            git config --global user.name "Test Test"
            bundle exec overcommit --sign
            bundle exec overcommit --sign pre-commit

            bundle exec overcommit --run
  tox:
    description: "Run tox"
    parameters:
      tox_arguments:
        type: string
        default: ''
        description: "Which tox arguments to pass"
    steps:
      - set_up_environment
      - run_with_languages:
          label: Test
          command: |
            # These will be used in post_gen_project.py while testing
            # the cookies, as well as by overcommit
            git config --global user.email "test@test.test"
            git config --global user.name "Test Test"
            # Coax overcommit into working
            bundle exec overcommit --sign
            bundle exec overcommit --sign pre-commit

            tox <<parameters.tox_arguments>>

jobs:
  overcommit:
    working_directory: ~/cookiecutter-ruby
    docker:
      - image: apiology/circleci-python:latest
    steps:
      - overcommit
  build:
    working_directory: ~/cookiecutter-ruby
    docker:
      - image: apiology/circleci-python:latest
    steps:
      - restore_cache:
          key: child-gems-v1-{{ checksum "{{cookiecutter.project_slug}}/Gemfile" }}
      - unless:
          condition:
            equal: [<< pipeline.git.branch >>, "main"]
          steps:
            # skip tox to speed things by not installing another
            # virtualenv, and only run in default Python version.
            - set_up_environment
            - run_with_languages:
                label: Typecheck
                command: |
                  make citypecheck citypecoverage
            - run_with_languages:
                label: Test
                command: |
                  # These will be used in post_gen_project.py while testing
                  # the cookies, as well as by overcommit
                  git config --global user.email "test@test.test"
                  git config --global user.name "Test Test"
                  # Coax overcommit into working
                  bundle exec overcommit --sign
                  bundle exec overcommit --sign pre-commit

                  make citest cicoverage
      - save_cache:
          key: child-gems-v1-{{ checksum "{{cookiecutter.project_slug}}/Gemfile" }}
          paths:
            - "vendor/bundle"
      - when:
          condition:
            equal: [<< pipeline.git.branch >>, "main"]
          steps:
            - tox
    # This seemed to shave 5ish% of the build time off when added
    resource_class: large

workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 6"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
      - overcommit
  overcommit:
    jobs:
      - overcommit
  build:
    jobs:
      - build
