---
version: 2.1

commands:
  run_with_languages:
    description: "Run the given command in an environment that includes relevant langauges in the PATH"
    parameters:
      command:
        type: string
        description: "What command to execute"
      label:
        type: string
        description: "What to label the run"
        default: <<parameters.command>>
    steps:
      - run:
          name: <<parameters.label>>
          command: |
            export PATH="${HOME}/.pyenv/bin:${PATH}"
            export PATH="${HOME}/.rbenv/bin:${HOME}/.rbenv/shims:${PATH}"
            export PATH="${HOME}/project/node_modules/.bin:${PATH}"
            eval "$(pyenv init --path)"
            eval "$(pyenv virtualenv-init -)"
            eval "$(rbenv init -)"
            # keep this in a single place for both main and child builds for cachability
            export BUNDLE_PATH="$(pwd)/vendor/bundle"

            <<parameters.command>>
          environment:
            # https://app.circleci.com/pipelines/github/apiology/cookiecutter-pypackage/4/workflows/29074dc8-944c-4600-8aaa-5116575fed90/jobs/4
            "LC_ALL": "C.UTF-8"
            "LANG": "C.UTF-8"
  set_up_environment:
    description: "Install source environment"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gems-v3-{% raw %}{{ checksum "Gemfile.lock" }}{% endraw %}-
            - gems-v3-
            - gems-
      - restore_cache:
          keys:
            - wheels-v1-3.12.7-{% raw %}{{ checksum "requirements_dev.txt" }}{% endraw %}
            - wheels-v1-3.12.7-
            - wheels-v1-
            - wheels-
      - run:
          name: Initialize packages
          command: |
            # measuring slows down the script - only enable when you
            # want to debug where this is spending time

            # export FIX_SH_TIMING_LOG=/tmp/fix_sh_timing.log

            export BUNDLE_PATH="$(pwd)/vendor/bundle"
            './fix.sh'
      - store_artifacts:
          path: /tmp/fix_sh_timing.log
      - run:
          name: Verify Gemfile.lock
          command: |
            if ! git diff --exit-code Gemfile.lock
            then
              >&2 echo "Please resolve changes to Gemfile.lock after bundle install to avoid caching difficulties"
              exit 1
            fi
      - save_cache:
          key: gems-v3-{% raw %}{{ checksum "Gemfile.lock" }}{% endraw %}-{% raw %}{{ checksum ".ruby-version" }}{% endraw %}
          paths:
            - "vendor/bundle"
            - ".yardoc"
      - save_cache:
          key: wheels-v1-3.12.7-{% raw %}{{ checksum "requirements_dev.txt" }}{% endraw %}
          paths:
            - "/home/circleci/.cache/pip/wheels"
            - "/home/circleci/.pyenv/versions/3.12.7/envs/{{cookiecutter.project_slug}}-3.12.7"
            - "/home/circleci/.pyenv/versions/{{cookiecutter.project_slug}}-3.12.7"
      - run:
          name: Download new circleci tool
          command: |
            curl -fLSs \
            https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | sudo bash
  quality:
    description: "Quality checks"
    steps:
      - set_up_environment
      - run_with_languages:
          label: Run overcommit
          command: |
            # Coax overcommit into working
            git config --global user.email "test@test.test"
            git config --global user.name "Test Test"
            bundle exec overcommit --sign
            bundle exec overcommit --sign pre-commit

            bundle exec overcommit --run
jobs:
  quality:
    working_directory: ~/{{cookiecutter.project_slug}}
    docker:
      - image: apiology/circleci:latest
    steps:
      - quality
  build:
    working_directory: ~/{{cookiecutter.project_slug}}
    docker:
      - image: apiology/circleci:latest
    steps:
      - set_up_environment
      - run_with_languages:
          label: Typecheck
          command: make citypecheck citypecoverage
      - run_with_languages:
          label: Test
          command: |
            make citest cicoverage
    # This seemed to shave 5ish% of the build time off when added
    resource_class: large

workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 6"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
      - quality
  quality:
    jobs:
      - quality
  build:
    jobs:
      - build
