---
version: 2.1

commands:
  run_with_languages:
    description: "Run the given command in an environment that includes relevant langauges in the PATH"
    parameters:
      command:
        type: string
        description: "What command to execute"
      label:
        type: string
        description: "What to label the run"
        default: <<parameters.command>>
    steps:
      - run:
          name: <<parameters.label>>
          command: |
            export PATH="${HOME}/.pyenv/bin:${PATH}"
            export PATH="${HOME}/.rbenv/bin:${HOME}/.rbenv/shims:${PATH}"
            export PATH="${HOME}/project/node_modules/.bin:${PATH}"
            eval "$(pyenv init --path)"
            eval "$(pyenv virtualenv-init -)"
            eval "$(rbenv init -)"

            # keep this in a single place for both main and child builds for cachability
            BUNDLE_PATH="$(pwd)/vendor/bundle"
            export BUNDLE_PATH
            GEM_HOME="${BUNDLE_PATH}"
            export GEM_HOME

            <<parameters.command>>
          environment:
            # https://app.circleci.com/pipelines/github/apiology/cookiecutter-pypackage/4/workflows/29074dc8-944c-4600-8aaa-5116575fed90/jobs/4
            "LC_ALL": "C.UTF-8"
            "LANG": "C.UTF-8"
  set_up_environment:
    description: "Install source environment"
    steps:
      - checkout
      - run:
          name: Update timestamps to original commit time
          command: |
            git ls-tree -r --name-only HEAD | while read filename; do \
              unixtime=$(git log -1 --format="%at" -- "${filename}")
              touchtime=$(date -d @$unixtime +'%Y%m%d%H%M.%S')
              touch -t ${touchtime} "${filename}"
            done
      - restore_cache:
          keys:
            - rbenv-v4-{% raw %}{{ checksum "Gemfile.lock" }}{% endraw %}-
            - rbenv-v4-
            - rbenv-
      - restore_cache:
          keys:
            - solargraph-v2-{% raw %}{{ checksum "Gemfile.lock" }}{% endraw %}-{% raw %}{{ .Branch }}{% endraw %}
            - solargraph-v2-{% raw %}{{ checksum "Gemfile.lock" }}{% endraw %}-
            - solargraph-v2-
            - solargraph-
      - restore_cache:
          keys:
            - pyenv-v2-{% raw %}{{ checksum "requirements_dev.txt" }}{% endraw %}
            - pyenv-v2-
            - pyenv-
      - run:
          name: Initialize packages
          command: |
            # measuring slows down the script - only enable when you
            # want to debug where this is spending time

            # export FIX_SH_TIMING_LOG=/tmp/fix_sh_timing.log

            BUNDLE_PATH="$(pwd)/vendor/bundle"
            export BUNDLE_PATH
            GEM_HOME="${BUNDLE_PATH}"
            export GEM_HOME

            './fix.sh'
      - store_artifacts:
          path: /tmp/fix_sh_timing.log
      - run:
          name: Verify Gemfile.lock
          command: |
            if ! git diff --exit-code Gemfile.lock
            then
              >&2 echo "Please resolve changes to Gemfile.lock after bundle install to avoid caching difficulties"
              exit 1
            fi
      - save_cache:
          key: rbenv-v4-{% raw %}{{ checksum "Gemfile.lock" }}{% endraw %}-{% raw %}{{ checksum ".ruby-version" }}{% endraw %}
          paths:
            - "Gemfile.lock.installed"
            - "types.installed"
            - "vendor/bundle"
            - "/home/circleci/.rbenv"
            - ".yardoc"
      - save_cache:
          key: pyenv-v2-{% raw %}{{ checksum "requirements_dev.txt" }}{% endraw %}
          paths:
            - "requirements_dev.txt.installed"
            - "/home/circleci/.cache/pip/wheels"
            - "/home/circleci/.pyenv"
      - run:
          name: Download new circleci tool
          command: |
            curl -fLSs \
            https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | sudo bash
  quality:
    description: "Quality checks"
    steps:
      - set_up_environment
      - run_with_languages:
          label: Run overcommit
          command: |
            # Coax overcommit into working
            git config --global user.email "test@test.test"
            git config --global user.name "Test Test"
            bundle exec overcommit --sign
            bundle exec overcommit --sign pre-commit

            bundle exec overcommit --run
      - run_with_languages:
          label: Run brakeman
          command: |
            bundle exec brakeman --no-pager --force
      - run_with_languages:
          label: Run Rubocop
          command: |
            bundle exec rubocop
      - run_with_languages:
          label: Ratchet rubocop quality
          command: |
            set -x
            bundle exec rubocop --regenerate-todo --no-exclude-limit --auto-gen-only-exclude --no-auto-gen-timestamp
            if [ -f .rubocop_todo.yml ]
            then
              git diff --exit-code .rubocop.yml
              git diff --exit-code .rubocop_todo.yml
            fi
  update_dependencies:
    description: "Update dependencies whose build may have triggered this build"
    parameters:
      gems:
        type: string
        description: "Space-separated list of gems to update"
    steps:
      - run_with_languages:
          label: Update dependencies
          command: |
            set -x
            for package in <<parameters.gems>>
            do
              REMOTE_VERSION=$(gem search "${package}" | \
               grep "${package}" | cut -d\( -f2 | cut -d\) -f1)
              BUNDLED_VERSION=$(bundle info "${package}" | \
                 head -1 | cut -d\( -f2 | cut -d\) -f1)
              if [ ${REMOTE_VERSION:?} == ${BUNDLED_VERSION:?} ]
              then
                continue
              fi

              bundle update --conservative "${package}"

              BUNDLED_VERSION=$(bundle info "${package}" | \
                 head -1 | cut -d\( -f2 | cut -d\) -f1)

              if [ ${REMOTE_VERSION:?} == ${BUNDLED_VERSION:?} ]
              then
                continue
              fi

              echo "Waiting for ${package} v${REMOTE_VERSION} to be"\
                   "available..."
              sleep 20
              bundle update "${package}"

              BUNDLED_VERSION=$(bundle info "${package}" | \
                 head -1 | cut -d\( -f2 | cut -d\) -f1)


              if [ ${REMOTE_VERSION:?} != ${BUNDLED_VERSION:?} ]
              then
                >&2 echo "Manually upgrade to ${package}"\
                         "v${REMOTE_VERSION}"
                exit 1
              fi
            done
            if [ -z "$(git status --porcelain Gemfile.lock)" ]
            then
              echo "No updates needed"
              exit 0
            fi
            # Push any dependency gem updates
            git config user.email 'vince@broz.cc'
            git config user.name 'Vince Broz'
            git status
            # bundle exec so that overcommit is used from Gemfile for
            # git hooks
            #
            # https://app.circleci.com/pipelines/github/apiology/"${package}"-rails/806/workflows/40fdf1ef-fa23-421b-a0f1-641ea0ed1641/jobs/1173
            #
            bundle exec overcommit --sign pre-commit
            bundle exec git commit -m "Bump dependency releases" Gemfile.lock || true
            OVERCOMMIT_DEBUG=1 bundle exec git push --set-upstream origin "${CIRCLE_BRANCH:?}"
            echo "Avoiding double build after git push"
            exit 1
jobs:
  quality:
    working_directory: ~/{{cookiecutter.project_slug}}
    docker:
      - image: cimg/base:current
    steps:
      - quality
  build:
    working_directory: ~/{{cookiecutter.project_slug}}
    docker:
      - image: cimg/base:current
    steps:
      - set_up_environment
{% if cookiecutter.use_checkoff %}      - when:
          condition:
            equal: [<< pipeline.git.branch >>, "main"]
          steps:
            - update_dependencies:
                gems: checkoff{% endif %}
      - run_with_languages:
          label: Typecheck
          command: make citypecheck citypecoverage
      - save_cache:
          key: solargraph-v2-{{ checksum "Gemfile.lock" }}-{{ checksum ".ruby-version" }}
          paths:
            - "/home/circleci/.cache/solargraph"
      - run_with_languages:
          label: Test
          command: |
            make citest cicoverage
    # This seemed to shave 5ish% of the build time off when added
    resource_class: large

workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 6"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
      - quality
  quality:
    jobs:
      - quality
  build:
    jobs:
      - build
